name: $(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    exclude:
    - "*"

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: templates
    type: git
    name: utilities/pipeline-scripts

variables:
- name: title
  value: ConfigToJson

- name: major-version
  value: 1

- name: minor-version
  value: 0

- name: patch-version
  value: $[counter(format('{0}.{1}', variables['major-version'], variables['minor-version']), 0)]

stages:
- stage: UnitTest
  displayName: '$(title) Build and Test'

  jobs:
  - job:
    displayName: Build and Test
    steps:
    - template: pipeline-templates/build-project.template.yaml@templates
      parameters:
        title: $(title)
        project: $(projectName)
        baseFolder: $(baseFolder)
        skipBuild: false

- stage: PackAndPublish
  dependsOn: UnitTest
  displayName: NuGet Pack and Publish

  jobs:
  - job:
    displayName: Pack and Publish
    steps:
    - template: pipeline-templates/nuget-pipeline.template.yaml.yaml@templates
      parameters:
        title: $(title)
        project: $(projectName)
        baseFolder:  $(baseFolder)
        skipBuild: true
        major-version: $(major-version)
        minor-version: $(minor-version)
        patch-version: $(patch-version)