name: $(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    exclude:
    - "*"

pool:
  vmImage: ubuntu-latest

variables:
- name: major-version
  value: '1'
- name: minor-version
  value: '0'
- name: patch-version
  value: $[counter(format('{0}.{1}', variables['major-version'], variables['minor-version']), 0)]

- name: full-version
  value: '$(major-version).$(minor-version).$(patch-version)'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/nupkgs'
    nobuild: false
    includesymbols: true
    includesource: true
    versioningScheme: byEnvVar
    versionEnvVar: 'full-version'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'yozepi-nuget'