name: $(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    exclude:
    - "*"

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: templates
    type: git
    name: utilities/pipeline-scripts

variables:
- name: title
  value: ConfigToJson
  
- name: projectName
  value: yozepi.ConfigToJson/yozepi.ConfigToJson.csproj

- name: baseFolder
  value: /src

- name: majorVersion
  value: '0'

- name: minorVersion
  value: '1'

- name: patchVersion
  value: $[counter(format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0)]

stages:
# - stage: UnitTest
#   displayName: '$(title) Build and Test'

#   jobs:
#   - job:
#     displayName: Build and Test
#     steps:
#     - template: pipeline-templates/build-project.template.yaml@templates
#       parameters:
#         title: $(title)
#         project: $(projectName)
#         baseFolder: $(baseFolder)
#         skipBuild: false

- stage: PackAndPublish
  # dependsOn: UnitTest
  displayName: '$(variables.title)NuGet Pack and Publish'

  jobs:
  - job:
    displayName: Pack and Publish
    steps:
    - template: pipeline-templates/nuget-pipeline.template.yaml@templates
      parameters:
        title: $(title)
        project: $(projectName)
        baseFolder:  $(baseFolder)
        majorVersion: $(variables.majorVersion)
        minorVersion: $(variables.minorVersion)
        patchVersion: $(variables.patchVersion)