name: $(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    exclude:
    - "*"

pr:
 branches:
  include:
    - main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: templates
    type: git
    name: utilities/pipeline-scripts

variables:
- name: projectName
  value: ConfigToJson

stages:
- stage: UnitTestFramework
  displayName: ConfigToJson Unit Tests

  jobs:
  - job:
    displayName: Build and Test
    steps:
    - task: CmdLine@2
      inputs:
        script: 'ls'

    - template: pipeline-templates/build-project.template.yaml@templates
      parameters:
        project: $(projectName)
        baseFolder: /src
        skipBuild: true
